<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Account successfully created</name>
   <tag></tag>
   <elementGuidId>cee34fd4-a63f-48e4-994e-4ca7f5e4f4a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#alert-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d2be9718-793c-4566-a974-f5bbbdc654f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>alert-text</value>
      <webElementGuid>0efbd20f-ff97-4f45-9e90-6fb2bab78de9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Account successfully created</value>
      <webElementGuid>4b8b370d-78ca-4188-be9f-832ea387437c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;success&quot;)/div[@id=&quot;alert-text&quot;]</value>
      <webElementGuid>4118c7e4-37f0-40d7-aba5-2e8bc3f73d87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='alert-text']</value>
      <webElementGuid>aa3537ed-5465-46c2-9bc3-e51e4c33c259</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='success']/div</value>
      <webElementGuid>6eef623c-9650-42dc-8b59-11158f12d29c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password recovery'])[1]/preceding::div[30]</value>
      <webElementGuid>034bdb95-7767-4bf6-b588-53864da0111a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Support'])[1]/preceding::div[33]</value>
      <webElementGuid>31bba76f-e673-4f2f-9d24-42f3fea43d3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Account successfully created']/parent::*</value>
      <webElementGuid>d3fa4439-1277-4402-a604-39ae19780352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div</value>
      <webElementGuid>dd251a1b-49e6-4059-895a-e71677235b36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'alert-text' and (text() = 'Account successfully created' or . = 'Account successfully created')]</value>
      <webElementGuid>8f9156c7-a3a8-4329-b8e3-03c5da9e9788</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
