<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_land Islands_state</name>
   <tag></tag>
   <elementGuidId>0eb24c8a-6f4e-4002-a129-02f352773e1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;state&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='state']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d67865ff-97c5-460e-92d9-7b205a082ae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>state</value>
      <webElementGuid>08cf3076-ad10-4850-8b88-e1834dc773d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c3d81ae3-1fee-458b-b65e-927ea97c0b2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control border-grey</value>
      <webElementGuid>96dc49eb-3ac7-4883-bafb-63fbfa38fa38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input your state</value>
      <webElementGuid>d47a3a93-6829-40ba-9760-a0d49c9a5c51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;state_input_wrapper&quot;)/input[@class=&quot;form-control border-grey&quot;]</value>
      <webElementGuid>e2ce63df-fc10-441d-9437-10f7ad03471a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='state']</value>
      <webElementGuid>96eb23f8-4837-4700-bad8-a93a70fab308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='state_input_wrapper']/input</value>
      <webElementGuid>8a751b90-1527-475a-b25c-dd2e206706a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[4]/input</value>
      <webElementGuid>64f6997a-35b0-47e4-ac7e-bcb8b97d2b67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'state' and @type = 'text' and @placeholder = 'Input your state']</value>
      <webElementGuid>61dbd08c-7114-45f4-87fd-af62ade493fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
