<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Log Out_fa fa-key</name>
   <tag></tag>
   <elementGuidId>f8d67ed1-4dde-4713-b183-f29d01513206</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-key</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='mp_main_header']/div/div[2]/ul/li/ul/li/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>a874b413-9a3b-4ad1-bdf0-d9e3748a0e0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-key</value>
      <webElementGuid>f9cb8e1b-3506-470f-b9c9-9eabf70c2b60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mp_main_header&quot;)/div[@class=&quot;navbar-header&quot;]/div[@class=&quot;top-nav&quot;]/ul[@class=&quot;nav pull-right top-menu&quot;]/li[@class=&quot;dropdown open&quot;]/ul[@class=&quot;dropdown-menu extended logout&quot;]/li[@class=&quot;logout-btn&quot;]/a[1]/i[@class=&quot;fa fa-key&quot;]</value>
      <webElementGuid>45702115-e7c9-4f27-97ee-40e75ef38599</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='mp_main_header']/div/div[2]/ul/li/ul/li/a/i</value>
      <webElementGuid>9087d574-1d64-4885-bbd2-4f0b4b6a0cf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li/a/i</value>
      <webElementGuid>fce3280e-ea25-4519-ad53-3e6d5ffd255e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
